/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fpapi_Lib */

#ifndef _Included_com_example_fpapi_Lib
#define _Included_com_example_fpapi_Lib



#define			OK							0
#define			FAIL						-1
#define			ENROLL_NOT_YET				-7


#define		TEMPLATE_LEN			512

enum QUALITY_PARA
{
	QUALITY_A=65, QUALITY_B, QUALITY_C, QUALITY_D, QUALITY_E
};


#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_example_fpapi_Lib_JavaFP_Start(JNIEnv * env, jobject thiz,jint Width,jint Height);
/*
Width, Height : [Input] ]Set the Image Size
return OK if no error
*/
JNIEXPORT jint JNICALL Java_com_example_fpapi_Lib_JavaFP_End(JNIEnv * env, jobject thiz);
/*
return OK if no error
*/
JNIEXPORT jint JNICALL Java_com_example_fpapi_Lib_JavaFP_Quality(JNIEnv * env, jobject thiz,jbyteArray lpImage);
/*
lpImage : [Input] ] the Image Buffer of Width * Height
return OK if the image quality is OK
*/
JNIEXPORT jint JNICALL Java_com_example_fpapi_Lib_JavaFP_Remove(JNIEnv * env, jobject thiz,jbyteArray lpImage);
/*
lpImage : [Input] ] the Image Buffer of Width * Height
return OK if no finger is on the reader
*/
JNIEXPORT jint JNICALL Java_com_example_fpapi_Lib_JavaFP_Template(JNIEnv * env, jobject thiz,jbyteArray rRawTemplate);
/*
rRawTemplate : [Output] ] the Template Buffer of 512 Bytes
return OK if no error
*/
JNIEXPORT jint JNICALL Java_com_example_fpapi_Lib_JavaFP_Enroll(JNIEnv * env, jobject thiz,jbyteArray RawTemplate,jbyteArray rEnrlTemplate );
/*
RawTemplate : [Input] ] the Template Buffer by FP_Template
rEnrlTemplate : [Output] ] the Template Buffer by FP_Enroll
return -7 if not yet OK
return 65~68 if OK
*/
JNIEXPORT jint JNICALL Java_com_example_fpapi_Lib_JavaFP_EndEnroll(JNIEnv * env, jobject thiz);
/*
return OK if no error
*/
JNIEXPORT jint JNICALL Java_com_example_fpapi_Lib_JavaFP_Verify(JNIEnv * env, jobject thiz ,jbyteArray RawTemplate,jbyteArray EnrlTemplate,jbyte threshold,jbyteArray rScore );
/*
rRawTemplate : [Input] ] the Template Buffer by FP_Template
EnrlTemplate : [Input] ] the Template Buffer by FP_Enroll
threshold : [Input] 0~100, default : 50
rScore :  [Output] 0~100, the matching score

return OK if no error
*/

#ifdef __cplusplus
}
#endif
#endif
